// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import FadeController from "./fade_controller"
import ResetFormController from "./reset_form_controller"
import FromPostController from "./from_post_controller"
import RakutenSearchController from "./rakuten_search_controller"
import { Autocomplete } from "stimulus-autocomplete"

application.register("fade", FadeController)
application.register("reset-form", ResetFormController)
application.register("from-post", FromPostController)
application.register("rakuten-search", RakutenSearchController)
application.register("autocomplete", Autocomplete)